#!/usr/bin/env python3

"""
Allternit Brain — master pipeline

Runs all brain maintenance steps in order and produces a structured report:
1. audit-brain.js
2. validate-links.js
3. watch-brain.js --write
4. regenerate Dashboard/*.md from current state
5. print JSON/stdout report

Usage:
    python3 scripts/brain-pipeline.py [--write]

Without --write, the watcher runs but does not write .incoming/ files and
Dashboard files are not overwritten. With --write, it does both.
"""

import argparse
import json
import os
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional

BRAIN_ROOT = Path("/Users/joe/Desktop/Allternit/Allternit Brain")
OPS_SCRIPTS = BRAIN_ROOT / "Ops" / "scripts"
DASHBOARD_DIR = BRAIN_ROOT / "Dashboard"


def run_node(script_name: str, *args) -> Dict:
    """Run a Node script and return structured result."""
    script = OPS_SCRIPTS / script_name
    cmd = ["node", str(script), *args]
    try:
        proc = subprocess.run(
            cmd,
            cwd=BRAIN_ROOT,
            capture_output=True,
            text=True,
            timeout=120,
        )
        return {
            "script": script_name,
            "ok": proc.returncode == 0,
            "returncode": proc.returncode,
            "stdout": proc.stdout.strip(),
            "stderr": proc.stderr.strip(),
        }
    except subprocess.TimeoutExpired:
        return {
            "script": script_name,
            "ok": False,
            "returncode": -1,
            "stdout": "",
            "stderr": "timeout",
        }
    except Exception as e:
        return {
            "script": script_name,
            "ok": False,
            "returncode": -1,
            "stdout": "",
            "stderr": str(e),
        }


def parse_audit(stdout: str) -> Dict:
    """Parse the plain-text output of audit-brain.js into structured data."""
    result = {
        "ok": "Stale (> 30 days): 0" in stdout and "Missing required frontmatter" in stdout and "Invalid status or date: 0" in stdout,
        "total": 0,
        "ok_count": 0,
        "stale": [],
        "missing_frontmatter": [],
        "invalid": [],
    }
    total_match = re.search(r"Scanned:\s*(\d+)\s+markdown files", stdout)
    if total_match:
        result["total"] = int(total_match.group(1))
    ok_match = re.search(r"OK:\s*(\d+)", stdout)
    if ok_match:
        result["ok_count"] = int(ok_match.group(1))

    # Extract stale docs
    stale_section = re.search(r"Stale \(> 30 days\):.*?(?:\n\n|\n(?:[^-]|$))", stdout, re.DOTALL)
    if stale_section and "0 stale" not in stdout:
        result["stale"] = [line.strip("- ").strip() for line in stale_section.group(0).splitlines() if line.strip().startswith("-")]

    return result


def find_markdown_files(root: Path) -> List[Path]:
    files = []
    for p in root.rglob("*.md"):
        if ".git" in p.parts or "node_modules" in p.parts:
            continue
        files.append(p)
    return files


def parse_frontmatter(path: Path) -> Optional[Dict]:
    text = path.read_text(encoding="utf-8")
    match = re.match(r"^---\s*\n(.*?)\n---\s*\n", text, re.DOTALL)
    if not match:
        return None
    fm = {}
    for line in match.group(1).splitlines():
        if ":" in line:
            k, v = line.split(":", 1)
            fm[k.strip()] = v.strip()
    return fm


def regenerate_dashboards(audit: dict) -> None:
    """Regenerate Dashboard/*.md from current brain state."""
    today_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    # Stale list
    stale_lines = []
    for item in audit.get("stale", []):
        stale_lines.append(f"| {item} | — | stale | > 30 days |")

    stale_md = f"""---
doc: dashboard
updated: {today_str}
status: active
---

# Stale Docs

_Last regenerated by `brain-pipeline` on {today_str}._

| Doc | Updated | Status | Age |
|-----|---------|--------|-----|
{chr(10).join(stale_lines) if stale_lines else "| _No stale docs._ | | | |"}

## How to refresh

Open each stale doc, review it, update the `updated:` frontmatter to today's date, and commit.
"""
    (DASHBOARD_DIR / "Stale.md").write_text(stale_md, encoding="utf-8")

    # File count summary
    all_files = find_markdown_files(BRAIN_ROOT)
    status_counts = {}
    for f in all_files:
        fm = parse_frontmatter(f)
        if fm:
            status = fm.get("status", "unknown")
            status_counts[status] = status_counts.get(status, 0) + 1

    now_md = f"""---
doc: dashboard
updated: {today_str}
status: active
---

# Now — Active Work

_Last regenerated by `brain-pipeline` on {today_str}._

## Brain snapshot

- Total docs: {len(all_files)}
- Audit OK: {audit.get("ok_count", 0)} / {audit.get("total", 0)}
- Status mix: {", ".join(f"{k}: {v}" for k, v in sorted(status_counts.items()))}

## Active projects

See [Projects/](../Projects/INDEX.md) for the full list.

## Up next

_Edit this section by hand; the pipeline preserves it if present._
"""
    (DASHBOARD_DIR / "Now.md").write_text(now_md, encoding="utf-8")


def main():
    parser = argparse.ArgumentParser(description="Allternit Brain master pipeline")
    parser.add_argument("--write", action="store_true", help="Write .incoming/ updates and regenerate dashboards")
    args = parser.parse_args()

    report = {
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "write_mode": args.write,
        "steps": [],
    }

    # Step 1: audit
    audit_result = run_node("audit-brain.js")
    audit_result["parsed"] = parse_audit(audit_result["stdout"])
    report["steps"].append(audit_result)

    # Step 2: validate links
    link_result = run_node("validate-links.js")
    report["steps"].append(link_result)

    # Step 3: watcher
    watcher_args = ["--write"] if args.write else []
    watcher_result = run_node("watch-brain.js", *watcher_args)
    report["steps"].append(watcher_result)

    # Step 4: regenerate dashboards
    dashboard_result = {"regenerated": False}
    if args.write:
        try:
            regenerate_dashboards(audit_result["parsed"])
            dashboard_result["regenerated"] = True
        except Exception as e:
            dashboard_result["error"] = str(e)
    report["steps"].append(dashboard_result)

    # Print report
    print(json.dumps(report, indent=2))

    # Exit non-zero if any step failed
    failed = [s for s in report["steps"] if not s.get("ok", True)]
    if failed:
        sys.exit(1)


if __name__ == "__main__":
    main()
